### ISSUE TITLE
Design the storage space for reports on Alpha 

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#104]
This design is concerned with 
  - Uploading a generated report to the target directory 
  - Associating the uploaded report with a specified product
  - Computing the download for each product 

We need to leverage the downloadable product to manage the associated report(s).

**Comment by NXdriveBeta** [comment]
I still download empty file from alpha. Downloading from beta is ok.

**Comment by NXdriveBeta** [comment]
download should be fixed. Closing issue.
