### ISSUE TITLE
Improve alerts and notifications 

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#109]
Alerts are used for displaying the errors as the result of running user requests. Alerts are designed such that users' attentions must be shifted to them. Therefore, alerts must be noticable. and obvious. For that purpose, alerts should meet up with the following checks:
  - Alerts should be visible in the current view of a user, i.e., its position should be fixed on the screen or should stay very close to the user's current operation
  - Do not automatically dismiss alerts
  
Notifications can be ignored by users and they are designed to be undisruptive.

**Comment by xlongtang** [comment]
Still needs some structure refactoring ... I will update this ticket soon ...

**Comment by NXdriveBeta** [comment]
Have changed most "page not found" cases. Redirect them to certain pages with notifications this way the workflow should be smooth even if anything went wrong.
