### ISSUE TITLE
Implement simplified page (page without header and footer) for Beta system

### ISSUE THREAD

**Issue by NXdriveBeta** [NXdriveBeta/CSAT#115]

**Comment by NXdriveBeta** [comment]
When user checkout reports in Beta system.

**Comment by xlongtang** [comment]
Replace simplified with s or v, and the default value is false ... 
The client is supposed to append right parameter when displaying this page ...

**Comment by xlongtang** [comment]
The flag for controlling whether the footer and header are visible should be carried over from page to page. In other words, if one page is displayed without the header and footer, then any link on this page should lead to page without any header or footer.  

We need to a better solution than changing pages one by one.

**Comment by NXdriveBeta** [comment]
Also the download url in the completed page is not fixed yet.

**Comment by NXdriveBeta** [comment]
To add the download link in Completed page, need to fix the caller in controller. 

Do we have to use base.Completed()?

**Comment by NXdriveBeta** [comment]
After checkout complete, there might be multiple items in one order.  I will redirect customer to the order detail page. Only problem is that the download link in the receipt page is little bit small.

**Comment by NXdriveBeta** [comment]
only checkout page has some glitch, shouldn't allow remove from cart in simplified view.
