### ISSUE TITLE
Processing an invitation link from an email

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#120]
Please check if any of any issue may exist  for the following cases when a user clicks an invitation link in his/her email. 
1. This user has already signed in our system (in the default browser) but this user is using a different account than the activation link is intended for;
2. This user has already signed in our system (in the default browser) and this user is using the same account as the activation link is intended for;
3. This user has not signed in ...

**Comment by xlongtang** [comment]
A first question we need to figure out is: Is the invitation link specific to a user and/or an organization?

**Comment by NXdriveBeta** [comment]
1. **result: will redirect to current user's dashboard**
2. signed in user will see a invitation at their dashboard, this page is well refined
3. If user is not signed in, will go to registration page, email field is filled out for the user, user can still edit email.

**Comment by xlongtang** [comment]
For Case 1, we need to let the user know that he/she has processed this invitation. 
One option is that: Calling AddSuccessNotification in the controller ...
Another option is that: A separate page is committed for this ...

Currently, let's use Case 1.

**Comment by NXdriveBeta** [comment]
Closing this issue as the controller will redirect user to switch account page if logged in user email is not the same as invited user email.
