### ISSUE TITLE
Extend ProjectModel to include required information

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#74]
Required information as below:
  - Total progress (answered questions/total questions)
  - Current user's progress, If this user has any role (answered questions/total questions)
  - Project state
  - Project description
  - Owner display name
  - Owner email
  - Last edited (last activity)

**Comment by NXdriveBeta** [comment]
Project description is called 'Desc'
State is called 'Status'

**Comment by NXdriveBeta** [comment]
New fields:
ProjectActivityModel LastActivity
string OwnerName
string OwnerEmail
double TotalProgress
double CurrentUserProgress
