### ISSUE TITLE
Need statistics API for a project

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#77]
First API is required for returning the detailed progress information for a project.  The API expects to take the UUID of a project as input, and outputs an array of progresses. Each progress describes the following information
  - Member name 
  - Member roles 
  - Member total questions 
  - Member answered questions 
  - Member email

**Comment by xlongtang** [comment]
This moment, the output is something like: 
{
  Members: [{
     Name: string;
     Email: string;
     Roles: string;
     TotalQuestions: number;
     ToalAnswers: number;   
}]
}

**Comment by NXdriveBeta** [comment]
count should be the same as group contributors number, not assigned role number

**Comment by NXdriveBeta** [comment]
Rest api is added. Need more test when total number of questions and answered question changes.
