### ISSUE TITLE
PrepareProjectModelAsync in CollaborationFactory needs to be fixed

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#79]
An issue is that IWorkContext may not make sense always; it does not create right information when used along with REST APIs. Thus, CurrentCustomer should be explicitly passed through method signatures.
For example, 
PrepareProjectModelAsync should be changed into PrepareProjectModelAsync(Project project, ProjectModel mode, Customer currentCustomer)

P.S. To avoid any pitfall, CollaborationFactory should not reference IWorkContext at all.

**Comment by NXdriveBeta** [comment]
Added customer and removed reference to _workcontext
