### ISSUE TITLE
Extends NotificationsApiController to mark a single message as read

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#81]
We still need one method for changing the state of a message to be "READ"
In NotificationsApiController (of the primary project), add a method for the above purpose.

**Comment by NXdriveBeta** [comment]
add a method in NotificationsApiController, allow them to mark a message as read

**Comment by NXdriveBeta** [comment]
new REST method is added. 

url;  [HttpPost("mark-as-read")]

parameter: messageId: int
