### ISSUE TITLE
Product API required

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#82]
Client needs to be able to create a product on demand. This product corresponds to a report, and part of confirmed information is:

  - project uuid
  - shopper id

Once a product has been successfully created, the product uuid should be returned.

**Comment by NXdriveBeta** [comment]
Alongside API, page workflow also needs discussion. 
In Beta
Option 1: open a sub page in current tab, once the payment is complete, sub page will disappear.
Option 2: open a new tab and jump to checkout page, user will have to manually close this tab.

**Comment by NXdriveBeta** [comment]
API is tested. Now re-designing the checkout page.

**Comment by NXdriveBeta** [comment]
https://themes.getbootstrap.com/preview/?theme_id=4231

checkout shopping cart page referring to above page.

**Comment by xlongtang** [comment]
More requirements on creating a product. 

If a product with the given SKU exists, do not recreate a new one. Instead, return the existing product's SKU.

**Comment by NXdriveBeta** [comment]
Product should be fixed by now, download type, maximum quantity 1, simple product
