### ISSUE TITLE
Extend the API for getting the list of projects for a customer

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#83]
- One optional query parameter is required to constrain the status of the projects in the output. For example, status = 50 means that the request is only interested in the set of completed projects. (Note that status should be type of the defined permitted enum .)

**Comment by NXdriveBeta** [comment]
new enumeration:
default : 0
incomplete: 10
completed: 50
archived: 100

When a project is created, the status is 10 (incomplete)

**Comment by NXdriveBeta** [comment]
status is changed.

technically a project's status cannot be 0 because projects start with "incomplete" and will always change between "incomplete" and "completed". "Archived" will be implemented later. client can specify status = 0 to return **all** projects disregard of status.
