### ISSUE TITLE
Enhance send message API in NotificationsApiController

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#85]
This Api expects to be capable of:
  - Indicating which project this message is for
  - Indicating who gives rise to this message...

**Comment by NXdriveBeta** [comment]
create a new class that inherit from PrivateMessageModel , replace list member type it in PrivateMessageListModel, add project uuid

**Comment by NXdriveBeta** [comment]
also add a new class that inherit from SendPrivateMessageModel, add project uuid

**Comment by NXdriveBeta** [comment]
also extend SendMessageByTargetCustomerEmail

**Comment by NXdriveBeta** [comment]
use project uuid

**Comment by NXdriveBeta** [comment]
project uuid now can be saved and loaded for the REST api. closing issue.
