### ISSUE TITLE
Update the link for "start to work"

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#87]
"start to work" supposes to link to a specific project, and our client is ready for that. 
Please get the link to be updated something like this: 
_storeulr_/workspace/#/user/projects/dashboard/_uuid_

Note that _storurl_ stands for the site URL, dynamically calculated (do not hardcode to be something like https://alpha.infobeyondtech.com). _uuid_ stands for a specific project UUID.

**Comment by NXdriveBeta** [comment]
url is updated on client side. Due to some issues in Beta, cannot directly go to a project's dashboard, landed on projects list instead.

**Comment by NXdriveBeta** [comment]
Link should be working now, Alpha is published.
