### ISSUE TITLE
Refining the APIs for the project activities 

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#92]
For adding an activity for a project, the server needs to clearly specify: 
 - The list of allowed activity types 
    e.g., the following can be a list 
    - Generating reports 
    - Reporting progresses 
    - and more 
- customer information should not be part of the request 
- API request data type does not follow the naming convention for C#
   - Capitalize the field (property) and use Ocamel

**Comment by NXdriveBeta** [comment]
public static string UpdateProjectPrefix = "UpdateProject";
        public static string UpdateContributorPrefix = "UpdateContributor";

        public static string ChangeProjectName = UpdateProjectPrefix + ".ChangeName";
        public static string ChangeProjectDescription = UpdateProjectPrefix + ".ChangeDescription";
        public static string ChangeProjectDueDate = UpdateProjectPrefix + ".ChangeDueDate";
        public static string ChangeProjectStatus = UpdateProjectPrefix + ".ChangeStatus";
        public static string ChangeProjectAvatar = UpdateProjectPrefix + ".ChangeAvatar";
        public static string ChangePriority = UpdateProjectPrefix + ".ChangePriority";
        public static string AddContributor = UpdateContributorPrefix + ".AddContributor";
        public static string RemoveContributor = UpdateContributorPrefix + ".RemoveContributor";

**Comment by NXdriveBeta** [comment]
todo: add enumerations for question related activities

generate reports, purchase reports, save answers

**Comment by NXdriveBeta** [comment]
three new enumerations has been added and tested. Will close the issue when the comment part is finished.

**Comment by NXdriveBeta** [comment]
coment is refined. For the rest api method, user have to specify the comment in their request. 

Also request no longer take activity type id but their keyword. If keyword doesn't match, activity will not be inserted.
