### ISSUE TITLE
Page to show all products that current customer relates to

### ISSUE THREAD

**Issue by NXdriveBeta** [NXdriveBeta/CSAT#98]
Show all the products related to current customer, 3 possible cases:
- purchased: will show a download report link
- in shopping cart: will show a link to shopping cart
- not in shopping cart: will give a link to add to shopping cart(ajax call, do not refresh page)

**Comment by xlongtang** [comment]
At this stage, for the third case, redirecting to the shopping cart page is good enough.

**Comment by NXdriveBeta** [comment]
page is published, download link is missing for the time-being, will re-open issue.
