### ISSUE TITLE
Enhance registeration result page

### ISSUE THREAD

**Issue by xlongtang** [NXdriveBeta/CSAT#99]
Some issues on this page:
1. Reword the paragraph: E.g., Remove "do us a favor"
2. Add some handy navigation buttons, e.g. Explore the product ...
3. Adjust the top and bottom margins such that they are symmetric

**Comment by NXdriveBeta** [comment]
1. changed it to:
<p>We have sent you an email to <a href="@Model.Email">@Model.Email</a>. Please check your email and follow the instructions inside, Thank you!</p>
